language: node_js
node_js:
- "10.15.2"
services:
- docker
cache: npm
scripts:
- npm build --production
- docker build -t mark9696/contacts-ui:v1 .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push mark9696/contacts-ui